"""
Account Pydantic Schemas
Defines request/response validation schemas using Pydantic.
Separates API contracts from database models.
"""
from pydantic import BaseModel

class AccountCreate(BaseModel):
    """
    Request schema for creating a new account.
    Validates input data from API clients.
    - name: Account holder's name (required)
    - balance: Initial account balance (required)
    """
    name: str
    balance: float

class AccountResponse(AccountCreate):
    """
    Response schema returned to API clients.
    Includes the 'id' field generated by the database.
    Inherits name and balance from AccountCreate.
    orm_mode=True enables conversion from SQLAlchemy model to Pydantic schema.
    """
    id: int

    class Config:
        # orm_mode: Allows Pydantic to read ORM model attributes directly
        # This lets FastAPI automatically convert SQLAlchemy models to JSON
        orm_mode = True